{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d9c4507d-7e35-4fd4-b666-fbbcb22f3b50",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Q1. Explain why we have to use the Exception class while creating a Custom Exception.\n",
    "\n",
    "\n",
    "\"\"\"In Python, the Exception class serves as the base class for all built-in exceptions. \n",
    "When creating a custom exception, it's recommended to derive your custom exception class \n",
    "from the built-in Exception class. There are several reasons why using the Exception class as\n",
    "the base for custom exceptions is beneficial:\n",
    "    1.Consistency and Convention: Deriving your custom exception class from Exception follows the \n",
    "    convention established by Python's exception hierarchy. This makes your custom exception consistent \n",
    "    with other exceptions in Python and makes it instantly recognizable as an exception.\n",
    "    \n",
    "    2. Hierarchy: By inheriting from Exception, your custom exception becomes part of the exception hierarchy. \n",
    "    This hierarchy allows you to handle your custom exception in a similar way to built-in exceptions. \n",
    "    For instance, you can catch your custom exception along with other exceptions using a common except block.\n",
    "    \n",
    "    3. Error Detection: Using a custom exception class derived from Exception helps in clearly \n",
    "    indicating that a specific error has occurred in your code. This enhances code readability and \n",
    "    helps others (including yourself) understand the nature of the issue.\n",
    "    \n",
    "    4. Exception Handling: By inheriting from Exception, your custom exception class inherits the \n",
    "    exception handling behavior of the base class. This means you can use the same techniques, \n",
    "    like try-except blocks, to handle your custom exceptions just like built-in exceptions.\n",
    "    \n",
    "    5. Better Tracebacks: Exception tracebacks provide information about the sequence of function calls\n",
    "    that led to the exception. By using a custom exception class derived from Exception, you ensure\n",
    "    that your custom exception's tracebacks provide meaningful information that aids in debugging.\n",
    "\n",
    "Example:\n",
    "    class CustomException(Exception):\n",
    "        def __init__(self, message):\n",
    "            self.message = message\n",
    "try:\n",
    "    age = int(input(\"Enter your age: \"))\n",
    "    if age < 0:\n",
    "        raise CustomException(\"Age cannot be negative.\")\n",
    "except CustomException as ce:\n",
    "    print(f\"Custom Exception: {ce.message}\")\n",
    "except ValueError:\n",
    "    print(\"Invalid input. Please enter a valid number.\")\"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "56d41699-5338-4bab-b912-1a44b64930b9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception\n",
      "  BaseException\n",
      "    object\n"
     ]
    }
   ],
   "source": [
    "#Q2. Q2. Write a python program to print Python Exception Hierarchy.\n",
    "\n",
    "\n",
    "def print_exception_hierarchy(exception_class, level=0):\n",
    "    indent = \"  \" * level\n",
    "    print(f\"{indent}{exception_class.__name__}\")\n",
    "    for base in exception_class.__bases__:\n",
    "        print_exception_hierarchy(base, level + 1)\n",
    "\n",
    "print_exception_hierarchy(Exception)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "14e9f679-90f8-4cb6-a3fc-0d3bcb3fa9de",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Q3. What errors are defined in the ArithmeticError class? Explain any two with an example.\n",
    "\n",
    "\n",
    "\"\"\"The ArithmeticError class in Python is the base class for all errors related to arithmetic operations. \n",
    "It is a subclass of the Exception class and is further subclassed into various more specific \n",
    "arithmetic error classes. Two commonly used subclasses of ArithmeticError are:\n",
    "    1. ZeroDivisionError: This error occurs when you try to divide a number by zero.\n",
    "    Example:\n",
    "        try:\n",
    "            result = 10 / 0\n",
    "        except ZeroDivisionError:\n",
    "            print(\"Error: Division by zero\")\n",
    "            \n",
    "    2. OverflowError: This error occurs when an arithmetic operation exceeds the limits of the data type.\n",
    "    Example:\n",
    "        import sys\n",
    "        try:\n",
    "            big_number = sys.maxsize\n",
    "            result = big_number * 10\n",
    "        except OverflowError:\n",
    "            print(\"Error: Arithmetic overflow\")\"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cace1840-acb0-4c41-bdcf-376020e9f4fd",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Q4. Why LookupError class is used? Explain with an example KeyError and IndexError.\n",
    "\n",
    "\n",
    "\"\"\"The LookupError class in Python is the base class for errors that occur when a lookup or \n",
    "indexing operation is performed on a sequence or mapping object and the specified key or index is not found. \n",
    "It is a subclass of the Exception class. This class is used to catch errors related to accessing \n",
    "elements that are not present in sequences (like lists, tuples, strings) or mappings (like dictionaries).\n",
    "\n",
    "Two common subclasses of LookupError are:\n",
    "    1. KeyError: This error occurs when you try to access a dictionary key that doesn't exist.\n",
    "    Example:\n",
    "        my_dict = {\"name\": \"John\", \"age\": 30}\n",
    "        try:\n",
    "            print(my_dict[\"city\"])\n",
    "        except KeyError:\n",
    "            print(\"Error: Key not found in dictionary\")\n",
    "    \n",
    "    2. IndexError: This error occurs when you try to access a list or tuple index that is out of range.\n",
    "    Example:\n",
    "        my_list = [10, 20, 30]\n",
    "        try:\n",
    "            print(my_list[5])\n",
    "        except IndexError:\n",
    "            print(\"Error: Index out of range\")\"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a90e5b45-c18a-4338-bbfd-151e69b2fd95",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Q5. Explain ImportError. What is ModuleNotFoundError?\n",
    "\n",
    "\n",
    "\"\"\"ImportError and ModuleNotFoundError are both exceptions in Python that occur when there are issues related \n",
    "to importing modules or packages.\n",
    "\n",
    "1. ImportError: This exception is raised when an import statement fails to locate and import a module. \n",
    "It can occur due to various reasons, such as the module being misspelled, the module not being installed, \n",
    "or an issue with the module's internal structure.\n",
    "Example:\n",
    "    try:\n",
    "        import non_existent_module\n",
    "    except ImportError:\n",
    "        print(\"Error: Module could not be imported\")\n",
    "\n",
    "2. ModuleNotFoundError: This exception is a subclass of ImportError and is raised specifically when Python \n",
    "cannot find the specified module to import. It was introduced in Python 3.6 to provide more informative \n",
    "error messages when a module is not found.\n",
    "Example:\n",
    "    try:\n",
    "        import non_existent_module\n",
    "    except ModuleNotFoundError:\n",
    "        print(\"Error: Module not found\")\"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "57ae94a4-9c94-4ae6-848e-6b321e980ba7",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Q6. List down some best practices for exception handling in python.\n",
    "\n",
    "\n",
    "\"\"\"Exception handling is an essential aspect of writing robust and reliable code. Here are some best practices \n",
    "for exception handling in Python:\n",
    "    1. Specific Exception Handling: Instead of using a generic except block, catch specific exceptions \n",
    "    that you expect might occur. This helps in understanding and addressing the exact issue.\n",
    "    \n",
    "    2. Use Multiple except Blocks: If you anticipate different types of exceptions, handle them using \n",
    "    separate except blocks. This makes your code more readable and maintainable.\n",
    "    \n",
    "    3. Avoid Bare except: Avoid using bare except statements without specifying the exception type.\n",
    "    This can hide errors and make debugging difficult.\n",
    "    \n",
    "    4. Use finally for Cleanup: Use the finally block to ensure that necessary cleanup actions are performed, \n",
    "    regardless of whether an exception was raised or not.\n",
    "    \n",
    "    5. Logging and Debugging: Use logging to record exceptions and error messages. This helps in tracking \n",
    "    issues and understanding the flow of the program during runtime.\n",
    "    \n",
    "    6. Custom Exception Classes: Create custom exception classes when you need to handle specific\n",
    "    scenarios that aren't covered by built-in exceptions. This improves code clarity.\n",
    "    \n",
    "    7. Avoid Overusing Exceptions for Control Flow: Exceptions should be used for handling exceptional \n",
    "    situations, not as a substitute for regular control flow.\n",
    "    \n",
    "    8. Don't Ignore Exceptions: Never ignore exceptions, as it can lead to unexpected behavior or errors \n",
    "    going unnoticed. Handle exceptions or log them appropriately.\n",
    "    \n",
    "    9. Use Context Managers: Utilize with statements and context managers for resources that need proper \n",
    "    initialization and cleanup, such as files (with open(...) as file:).\n",
    "    \n",
    "    10. Keep Exception Messages Informative: Exception messages should be informative and provide \n",
    "    details about what went wrong. This aids in troubleshooting.\n",
    "    \n",
    "    11. Avoid Deep Nesting: Excessive nested try and except blocks can make code difficult to read and maintain. \n",
    "    Refactor code to reduce nesting.\n",
    "    \n",
    "    12. Use try with Minimum Code: Wrap only the code that can potentially raise an exception in a try block, \n",
    "    keeping the rest of the code outside.\n",
    "    \n",
    "    13. Check Preconditions: Before executing potentially problematic code, check preconditions and \n",
    "    validate inputs to minimize the chances of exceptions.\n",
    "    \n",
    "    14. Use assert for Debugging: For debugging purposes, use the assert statement to check for conditions \n",
    "    that should always be true. This helps identify issues early.\n",
    "    \n",
    "    15. Use else Block: Use the else block after a try block to specify code that should run only when no \n",
    "    exceptions occur. This separates successful logic from error handling.\n",
    "    \n",
    "    16. Avoid Long try Blocks: Long try blocks can obscure the flow of the program. Break down complex logic \n",
    "    into smaller functions or blocks.\n",
    "    \n",
    "    17. Document Exception Handling: Clearly document exception handling strategies and the reasons behind \n",
    "    them in your code. This helps other developers understand your intent.\"\"\""
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
